name = "Untold Systems"
description = "Creating the future of digital media."
keywords = ""
image = "jake.webp"
theme = "dark"
primary_color = "#511223"
text_align = "center"
gtag_id = "G-XLJ81DCZFV"
base_url = "http://untoldsystems.github.io/links/"

[[sections]]
title = "Links"
description = "Look for us on these websites"
direction = "row"
item_style = "filled"
icon_size = "50px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/instagram/ffffff"
title = "Instagram"
url = "https://www.instagram.com/untoldsystems/"
[[sections.items]]
icon = "https://cdn.simpleicons.org/bluesky/ffffff"
title = "Bluesky"
url = "https://bsky.app/profile/untoldsystems.bsky.social"
[[sections.items]]
title = "Itch"
icon = "https://cdn.simpleicons.org/itch/ffffff"
url = "https://untoldsystems.itch.io/"

[[sections]]
item_style = "outline"
[[sections.items]]
title = "Our Website"
url = "https://untoldsystems.com/"